name: Conflict Report
description: Request your issue
title: "[CONFLICT] "
body:
  - type: markdown
    attributes:
      value: |
        충돌 기록
  - type: textarea
    id: conflict
    attributes:
      label: 충돌
      description: 충돌 사항
      placeholder: 수정을 통한 파일 변경
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: Todo
      description: 해결해야 할 점을 기록해주세요
      value: |
        - [ ] todo1
  - type: textarea
    id: etc
    attributes:
      label: 기타사항
      description: 추가로 기록이 필요한 경우 작성해주세요!